### ISSUE TITLE
useEffect 테스트 중 제대로 동작하지 않는 문제...

### ISSUE THREAD

**Issue by hoya74** [wikibook/springboot-react#2]
7장 146페이지의 useEffect 후크를 넣고 초기 렌더링시 콘솔에서 2번 기록을 합니다.
설명상으로 1번만 기록되어야 할텐데.... 무엇이 문제 일까요?

import React, { useState, useEffect } from 'react';

function Counter() {
    // 초기값이 0인 카운트 안내
    const [count, setCount] = useState(0);

    // 랜더링이 끝나면 매번 호출됨
    useEffect(() => {
        console.log('Counter value is now ' + count);
    }, [count]);

    return (
        <div>
            <p>{count}</p>
            <button onClick={() => setCount(count + 1)}>
                Increment
            </button>
        </div>
    );
}

export default Counter;

useEffect의 두번째 인수에 대한 설명은 맞는데....  첫번째 렌더링시 2번 기록을 하는 이유가 궁금합니다.

아래는 첫번째 렌더링 결과입니다.
![화면 캡처 2023-07-14 101758](https://github.com/wikibook/springboot-react/assets/47273615/4fb8350e-d919-4c17-a613-042b004165e6)

**Comment by hoya74** [comment]
index.js의 StrictMode 이것 때문이였네요.

<StrictMode> lets you find common bugs in your components early during development.

출처 : [https://react.dev/reference/react/StrictMode](https://react.dev/reference/react/StrictMode)

**Comment by wikibook** [comment]
@hoya74 님, 안녕하세요.
위키북스 담당자입니다.

말씀하신 문제를 확인해 보려고 했는데 해결책도 올려주셔서 감사합니다. :)

그럼 오늘도 좋은 하루 보내시고요,
즐거운 주말 맞이하세요.

고맙습니다.
