### ISSUE TITLE
14장 로그인 처리시 토큰값을 읽어오지 못하는 현상이 있습니다 ㅠㅠ

### ISSUE THREAD

**Issue by hoya74** [wikibook/springboot-react#3]
import React, { useState } from "react";
import { Button, Form, Input } from "antd";
import { SERVER_URL } from "../constants";

const LoingForm = () => {
    const [user, setUser] = useState({
        username: "",
        password: "",
    });
    const [isAuthenticated, setAuth] = useState(false);

    const handleChange = (event) => {
        setUser({ ...user, [event.target.name]: event.target.value });
    };

    const login = () => {
        console.log("login");
        console.log("user", user);
        fetch(SERVER_URL + "/login", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(user),
        })
            .then((res) => {
                console.log("res", res);
                console.log("res.headers", res.headers);
                const jwtToken = res.headers.get("Authorization");
                console.log("jwtToken", jwtToken);
                if (jwtToken !== null) {
                    sessionStorage.setItem("jwt", jwtToken);
                    setAuth(true);
                    //} else {
                    //    setOpen(true);
                }
            })
            .catch((err) => console.error(err));
    };

    return (
        <Form name="basic" labelCol={{ span: 8 }} wrapperCol={{ span: 16 }} style={{ maxWidth: 600 }} initialValues={{ remember: true }} autoComplete="off">
            <Form.Item label="Username" name="username" rules={[{ required: true, message: "Please input your username!" }]}>
                <Input name="username" onChange={handleChange} />
            </Form.Item>
            <Form.Item label="Password" name="password" rules={[{ required: true, message: "Please input your password!" }]}>
                <Input.Password name="password" onChange={handleChange} />
            </Form.Item>
            <Form.Item wrapperCol={{ offset: 8, span: 16 }}>
                <Button type="primary" onClick={login}>
                    Submit
                </Button>
            </Form.Item>
        </Form>
    );
};

export default LoingForm;

mui를 사용하지 않고 ant design을 사용한것 말고는 동일한데요.

로그인 화면
![image](https://github.com/wikibook/springboot-react/assets/47273615/0d429902-ed63-4101-a38b-0661cb5f7edb)

console.log 
![image](https://github.com/wikibook/springboot-react/assets/47273615/f700a0d7-d869-4bf7-ab24-1db385b95c56)

jwtToken이 null이 나오고 있습니다 ㅠㅠ
소스는 동일한데요...
status 200 나오는거 봐서는 문제가 없어 보이는데.....  왜  token 을 얻지 못할까요?

더하기1: SecurityConfig 파일 설정입니다.
![image](https://github.com/wikibook/springboot-react/assets/47273615/8460c39b-587c-47c3-8215-bcc95649c536)

더하기2: POST MAN으로 동작은 정상적입니다.
![image](https://github.com/wikibook/springboot-react/assets/47273615/0bd7d7c6-874a-4351-bab2-d9c6b064be9b)

동일한 Backend  소스를 react에서 호출할떄 결과와 POST MAN 호출할때 결과가 다릅니다.

**Comment by wikibook** [comment]
@hoya74 님, 안녕하세요.
위키북스 담당자입니다.

보내주신 내용을 확인했는데 보내주신 내용만으로는 명확한 원인을 파악하기 어렵습니다. 혹시 괜찮으시다면 전체 프로젝트(백엔드+프런트엔드)를 압축해서 보내주시면 확인해 보도록 하겠습니다.

그럼 오늘도 편안한 저녁시간 보내세요.
고맙습니다.

**Comment by hoya74** [comment]
frontend는 node_modules 빼고 압축해서 메일로 보내드리면 될까요?

**Comment by wikibook** [comment]
@hoya74 님, 안녕하세요.

말씀하신 것처럼 node_modules를 제외한 상태로 dylee@wikibook.co.kr로 부탁드립니다.

고맙습니다.

**Comment by hoya74** [comment]
@wikibook 메일전송을 하였습니다.
첨부파일은 구글정책상으로 바로 첨부가 안되어 드라이브에 넣고 링크 걸었습니다.
스프링부트 3.0.8 기준으로 테스트 중입니다. 
(SecurityConfig.java는 https://github.com/wikibook/springboot-react/issues/1 내용과 거의 동일합니다.)

**Comment by wikibook** [comment]
@hoya74 님, 안녕하세요.
보내주신 파일 잘 받았습니다.

보내주신 프로젝트를 대략적으로 살펴봤는데 데이터베이스 구성 및 실습 환경을 동일하게 맞춰야 해서 그런지 오류가 많이 생기네요. 저 또한 책 내용대로 처음부터 따라하는 식으로 진행하기에 확인하는 데 시간이 다소 걸릴 것 같고, 책 내용과 다르게 진행하신 부분에 대해서는 확인해 드리기 어렵다는 점을 미리 말씀드립니다.

그래서 다음 주 중반은 되어야 확인 가능할 것으로 보이는데요, 그 사이에 @hoya74 님께서도 책 내용 그대로 먼저 다시 한번 실습하시면서 진행해 보시는 건 어떠신지요?

참고 부탁드리고요, 오늘도 편안한 하루 보내세요.
고맙습니다.

**Comment by wikibook** [comment]
@hoya74 님, 안녕하세요.

Postman으로 헤더를 확인하던 차에 응답 헤더에 오타(`Authorazation`)가 있는 것을 확인했는데요, `JwtService` 클래스의 다음 줄을 수정하면 문제 없이 JWT 토큰이 콘솔에 출력되는 것을 확인했습니다.

~~~
return ResponseEntity.ok().header(HttpHeaders.AUTHORIZATION, "Bearer " + jwts).header(HttpHeaders.ACCESS_CONTROL_EXPOSE_HEADERS, "Authorazation").build();
~~~

==>

~~~
return ResponseEntity.ok().header(HttpHeaders.AUTHORIZATION, "Bearer " + jwts).header(HttpHeaders.ACCESS_CONTROL_EXPOSE_HEADERS, "Authorization").build();
~~~

그럼 확인 부탁드리고요, 오늘도 좋은 하루 보내세요.
고맙습니다.

**Comment by hoya74** [comment]
@wikibook 확인했습니다.
말씀해주신 부분을 수정하니 토큰값이 나오네요 ㅠㅠ

데이터베이스는 JPA hybernate 구성이기 때문에 자동으로 생성되는 DB를 사용하시면 Mysql DB or Maria DB 동일하게 테스트 해볼 수 있는걸로 압니다.

저의 오타때문에 고생하신듯하여 죄송하고 감사합니다.

**Comment by wikibook** [comment]
@hoya74 님, 안녕하세요.
확인 감사합니다.

우선 DB 접속 정보 및 DDL 생성을 자동으로 하도록 몇 가지 설정을 바꾸는 등의 작업을 하고 user 계정 정보를 별도로 입력하는 쿼리를 실행했더니 실습을 할 수 있게 되더라고요. :)

시간이 오래 걸릴 것 같았는데, 마침 오탈자가 금방 눈에 띄어서 어렵지 않게 해결할 수 있었습니다.
빠르게 해결되어 다행이고요, 남은 하루도 잘 마무리하시고 편안한 주말 맞이하시기 바랍니다.

고맙습니다.
